name: Pre-Migration

on:
push:
branches:
- main # Modify this to match your branch name

jobs:
check_repo_size:
runs-on: ubuntu-latest

steps:
- name: Check repository size
run: |
git gc --aggressive
git count-objects -vH

check_file_size:
runs-on: ubuntu-latest

steps:
- name: Checkout code
uses: actions/checkout@v2

- name: Check file size
run: |
find . -type f -size +100M -exec ls -lh {} \;
